version: "3"
services:
  django:
    image: python:2.7
    volumes:
    - ./:/code
    working_dir: /code
    expose:
    - 9000
    ports:
    - "9000:9000"
    command: /bin/bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:9000"
  angular:
    image: node:8.1.3
    volumes:
    - ./gameapp:/gameapp
    working_dir: /gameapp
    ports:
    - "3000:3000"
    links:
    - django
    command: /bin/bash -c "npm install && npm start"