# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='Comment text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(verbose_name='News text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=200, verbose_name='News title'),
        ),
    ]
